export const STUDENTS = [
  "Lê Thị Mai Anh",
  "Lê Văn Gia Bảo",
  "Trần Ngọc Bảo",
  "Nguyễn Thị Diệu Châu",
  "Lê Thị Kim Chi",
  "Đoàn Thùy Dương",
  "Trần Vi Minh Đạt",
  "Phạm Lê Hân",
  "Trần Việt Hoàng",
  "Nguyễn Thị Huệ",
  "Đỗ Thị Bích Huyền",
  "Lê Bảo Khang",
  "Dương Công Khánh",
  "Phan Trung Lộc",
  "Nguyễn Thị Ngọc Mai",
  "Lê Minh Ngọc",
  "Trương Gia Nguyên",
  "Đoàn Thị Yến Nhi",
  "Nguyễn Trần Uyễn Nhi",
  "Trần Hoài Như",
  "Lê Thị Diễm Phương",
  "Võ Văn Quân",
  "Phan Thi Như Quỳnh",
  "Nguyễn Trọng Oai Sang",
  "Châu Đình Tài",
  "Phạm Văn Thăng",
  "Lê Đình Thi",
  "Nguyễn Nhật Trung",
  "Trần Hà Trung",
  "Nguyễn Thị Cẩm Tú",
  "Nguyễn Thị Thảo Vy",
  "Ngô Thị Phi Yến",
  "Nguyễn Thị Hải Yến"
];

export const SUBJECTS = [
  "Toán",
  "Giáo dục thể chất",
  "Giáo dục quốc phòng và an ninh",
  "Lịch sử",
  "Địa lí",
  "Giáo dục kinh tế và pháp luật",
  "Vật lí",
  "Hoá học",
  "Sinh học",
  "Công nghệ",
  "Tin học",
  "Âm nhạc",
  "Mĩ thuật",
  "Hoạt động trải nghiệm, hướng nghiệp",
  "Nội dung giáo dục của địa phương"
];
